- type: job
  id: EMJobStationAdministrator
  name: em-job-name-station-administrator
  description: em-job-description-station-administrator
  playTimeTracker: EMJobStationAdministrator
  icon: "JobIconPassenger"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  setPreference: true
  canBeAntag: false
  access:
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: job
  id: EMJobStationOverwatch
  name: em-job-name-station-overwatch
  description: em-job-description-station-overwatch
  playTimeTracker: EMJobStationOverwatch
  icon: "JobIconPassenger"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  setPreference: true
  canBeAntag: false
  access:
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff