- type: department
  id: EMLogistics
  name: em-department-Logistics
  description: em-department-Logistics-description
  color: "#A46106"
  editorHidden: false
  roles:
  - EMJobLogisticsSupervisor
  - EMJobScout
  - EMJobMiner
  - EMJobLogisticsAssistant

- type: department
  id: EMMedical
  name: em-department-Medical
  description: em-department-Medical-description
  color: "#A46106"
  editorHidden: false
  roles:
  - EMJobMedicalSupervisor
  - EMJobMedic
  - EMJobChemist
  - EMJobMedicalAssistant

- type: department
  id: EMEngineering
  name: em-department-Engineering
  description: em-department-Engineering-description
  color: "#A46106"
  editorHidden: false
  roles:
  - EMJobEngineeringSupervisor
  - EMJobEngineer
  - EMJobAtmosphericEngineer
  - EMJobEngineeringAssistant

- type: department
  id: EMResearchDepartment
  name: em-department-Research
  description: em-department-Research-description
  color: "#A46106"
  editorHidden: false
  roles:
  - EMJobResearchSupervisor
  - EMJobResearcher
  - EMJobResearchAssistant

- type: department
  id: EMSecurity
  name: em-department-Security
  description: em-department-Security-description
  color: "#A46106"
  editorHidden: false
  roles:
  - EMJobSecuritySupervisor
  - EMJobSecurityDetective
  - EMJobBrigMaster
  - EMJobSecurityOfficer
  - EMJobSecurityAssistant

- type: department
  id: EMServices
  name: em-department-Services
  description: em-department-Services-description
  color: "#A46106"
  editorHidden: false
  roles:
  - EMJobServicesSupervisor
  - EMJobBotanist
  - EMJobChef
  - EMJobBartender
  - EMJobJanitor
  - EMJobActor
  - EMJobPriest
  - EMJobServiceAssistant

- type: department
  id: EMGuest
  name: em-department-Guest
  description: em-department-Guest-description
  color: "#A46106"
  editorHidden: false
  roles:
  - EMJobPassenger

- type: department
  id: EMAdministrative
  name: em-department-Administrative
  description: em-department-Administrative-description
  color: "#A46106"
  editorHidden: false
  roles:
  - EMJobStationAdministrator
  - EMJobStationOverwatch