- type: job
  id: EMJobPassenger
  name: em-job-name-passenger
  description: em-job-description-passenger
  playTimeTracker: EMJobPassenger
  icon: "EMJobIconPassenger"
  supervisors: job-supervisors-everyone
  setPreference: true
