- type: job
  id: EMJobLogisticsSupervisor
  name: em-job-name-logistics-supervisor
  description: em-job-description-logistics-supervisor
  playTimeTracker: EMJobLogisticsSupervisor
  icon: "EMJobIconLogisticsSupervisor"
  weight: 5
  supervisors: em-job-name-station-administrator
  access:
    - EMLogistics
    - EMScout
    - EMMiner
    - EMLogisticsSupervisor
    - EMAdministrative
    - EMMaintenance
    - EMSpace
  setPreference: true
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: CommandStaff

- type: job
  id: EMJobScout
  name: em-job-name-scout
  description: em-job-description-scout
  playTimeTracker: EMJobScout
  icon: "EMJobIconScout"
  supervisors: em-job-name-logistics-supervisor
  access:
    - EMLogistics
    - EMScout
    - EMMaintenance
    - EMSpace
  setPreference: true

- type: job
  id: EMJobMiner
  name: em-job-name-miner
  description: em-job-description-miner
  playTimeTracker: EMJobMiner
  icon: "EMJobIconMiner"
  supervisors: em-job-name-logistics-supervisor
  access:
    - EMLogistics
    - EMMiner
    - EMMaintenance
    - EMSpace
  setPreference: true

- type: job
  id: EMJobLogisticsAssistant
  name: em-job-name-logistics-assistant
  description: em-job-description-logistics-assistant
  playTimeTracker: EMJobLogisticsAssistant
  icon: "EMJobIconLogisticsAssistant"
  supervisors: em-job-name-logistics-supervisor
  access:
    - EMLogistics
    - EMMaintenance
    - EMSpace
  setPreference: true
