- type: job
  id: EMJobMedicalSupervisor
  name: em-job-name-medical-supervisor
  description: em-job-description-medical-supervisor
  playTimeTracker: EMJobMedicalSupervisor
  icon: "EMJobIconMedicalSupervisor"
  weight: 5
  supervisors: em-job-name-station-administrator
  access:
    - EMMedical
    - EMMedic
    - EMChemist
    - EMMedicalSupervisor
    - EMAdministrative
    - EMMaintenance
    - EMSpace
  setPreference: true
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: CommandStaff

- type: job
  id: EMJobMedic
  name: em-job-name-medic
  description: em-job-description-medic
  playTimeTracker: EMJobMedic
  icon: "EMJobIconMedic"
  supervisors: em-job-name-medical-supervisor
  access:
    - EMMedical
    - EMMedic
    - EMMaintenance
  setPreference: true

- type: job
  id: EMJobChemist
  name: em-job-name-chemist
  description: em-job-description-chemist
  playTimeTracker: EMJobChemist
  icon: "EMJobIconChemist"
  supervisors: em-job-name-medical-supervisor
  access:
    - EMMedical
    - EMChemist
    - EMMaintenance
  setPreference: true

- type: job
  id: EMJobMedicalAssistant
  name: em-job-name-medic-assistant
  description: em-job-description-medic-assistant
  playTimeTracker: EMJobMedicalAssistant
  icon: "EMJobIconMedicalAssistant"
  supervisors: em-job-name-medical-supervisor
  setPreference: true
  access:
    - EMMedical
