- type: job
  id: EMJobServicesSupervisor
  name: em-job-name-services-supervisor
  description: em-job-description-services-supervisor
  playTimeTracker: EMJobServicesSupervisor
  icon: "EMJobIconServicesSupervisor"
  weight: 5
  supervisors: em-job-name-station-administrator
  access:
    - EMServices
    - EMPriest
    - EMActor
    - EMJanitor
    - EMBar
    - EMKitchen
    - EMBotany
    - EMServicesSupervisor
    - EMAdministrative
    - EMMaintenance
  setPreference: true
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: CommandStaff

- type: job
  id: EMJobPriest
  name: em-job-name-priest
  description: em-job-description-priest
  playTimeTracker: EMJobPriest
  icon: "EMJobIconPriest"
  supervisors: em-job-description-services-supervisor
  access:
    - EMServices
    - EMPriest
    - EMMaintenance
  setPreference: true

- type: job
  id: EMJobActor
  name: em-job-name-actor
  description: em-job-description-actor
  playTimeTracker: EMJobActor
  icon: "EMJobIconActor"
  supervisors: em-job-description-services-supervisor
  access:
    - EMServices
    - EMActor
    - EMMaintenance
  setPreference: true

- type: job
  id: EMJobJanitor
  name: em-job-name-janitor
  description: em-job-description-janitor
  playTimeTracker: EMJobJanitor
  icon: "EMJobIconJanitor"
  supervisors: em-job-description-services-supervisor
  access:
    - EMServices
    - EMJanitor
    - EMMaintenance
  setPreference: true

- type: job
  id: EMJobBartender
  name: em-job-name-bartender
  description: em-job-description-bartender
  playTimeTracker: EMJobBartender
  icon: "EMJobIconBartender"
  supervisors: em-job-description-services-supervisor
  access:
    - EMServices
    - EMBar
    - EMMaintenance
  setPreference: true

- type: job
  id: EMJobChef
  name: em-job-name-chef
  description: em-job-description-chef
  playTimeTracker: EMJobChef
  icon: "EMJobIconChef"
  supervisors: em-job-description-services-supervisor
  access:
    - EMServices
    - EMKitchen
    - EMBotany
    - EMMaintenance
  setPreference: true

- type: job
  id: EMJobBotanist
  name: em-job-name-botanist
  description: em-job-description-botanist
  playTimeTracker: EMJobBotanist
  icon: "EMJobIconBotanist"
  supervisors: em-job-description-services-supervisor
  access:
    - EMServices
    - EMBotany
    - EMMaintenance
  setPreference: true

- type: job
  id: EMJobServiceAssistant
  name: em-job-name-services-assistant
  description: em-job-description-services-assistant
  playTimeTracker: EMJobServiceAssistant
  icon: "EMJobIconServiceAssistant"
  supervisors: em-job-description-services-supervisor
  access:
    - EMServices
  setPreference: true
